name: asan_yab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: any
  path_provider: ^2.0.15
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4
  upgrader: ^7.1.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  awesome_snackbar_content: ^0.1.3
  flutterflow_paginate_firestore: ^1.0.3+1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Shabnam
      fonts:
        - asset: fonts/Shabnam.ttf

