name: asan_yab
description: A new Flutter project.
publish_to: 'none'
version:  1.0.9+30
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: any
  cloud_firestore: any
  cupertino_icons: any
  dio: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: any
  google_fonts: any
  http: any
  intl: any
  path_provider: any
  smooth_page_indicator: any
  sqflite: any

  connectivity_plus: any
  awesome_snackbar_content: any
  flutterflow_paginate_firestore: any
  photo_view: any
  flutter_launcher_icons: any
  url_launcher: any
  flutter_native_splash: any
  change_app_package_name: any
  new_version_plus: any
  flutter_riverpod: any
  logging: any
  geolocator: any
  geocoding: any
  google_maps_flutter: any
  location: any
  typesense: any
  firebase_analytics: any
  firebase_messaging: any
  flutter_local_notifications: any
  firebase_auth: any
  email_validator: any
  shared_preferences: any
  image_picker: any
  file_picker: any
  clipboard: any
  flutter_popup_menu_button: any
  flutter_rating_bar: any

  easy_localization: any
  cloud_functions: any
  freezed: any
  freezed_annotation: any
  json_annotation: any
  build_runner: any
  json_serializable: any
  fluttertoast: any
  emoji_picker_flutter: any
  timeago: any
  lazy_load_scrollview: any
  image_cropper: any
  riverpod_annotation: any
  riverpod_generator: any
  riverpod_lint: any
  cached_network_image: any
  scrollable_positioned_list: any
  popover: any
  loading_animation_widget: any
  flutter_notification_channel: any
  flutter_emoji_gif_picker: any

dependency_overrides:
  web: any




flutter_native_splash:
  color: '#ffffff'
  image: 'assets/asan_yab.png'
  color_dark: '#2D3339'


  android: true
  ios: true
  web: false



dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter





flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Shabnam
      fonts:
        - asset: fonts/Shabnam.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/asan_yab.jpg"
  background_color: "#ffffff"





