// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj3JNQjtnDdynI47d3oC-OnsNDeV67sJ8',
    appId: '1:669397322687:web:e333fa9076974fb18faf0a',
    messagingSenderId: '669397322687',
    projectId: 'asan-yab-356f7',
    authDomain: 'asan-yab-356f7.firebaseapp.com',
    storageBucket: 'asan-yab-356f7.appspot.com',
    measurementId: 'G-WLBL10JPR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuoy2gkv9K0CdBcW1K7wCcgOm8C8_GaIg',
    appId: '1:669397322687:android:31d9317949ff3b3f8faf0a',
    messagingSenderId: '669397322687',
    projectId: 'asan-yab-356f7',
    storageBucket: 'asan-yab-356f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBar4vPOSw96fu-NWYW5dgQLRXfx8dToZE',
    appId: '1:669397322687:ios:ce04c094137eaf218faf0a',
    messagingSenderId: '669397322687',
    projectId: 'asan-yab-356f7',
    storageBucket: 'asan-yab-356f7.appspot.com',
    iosBundleId: 'com.example.asanYab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBar4vPOSw96fu-NWYW5dgQLRXfx8dToZE',
    appId: '1:669397322687:ios:ce04c094137eaf218faf0a',
    messagingSenderId: '669397322687',
    projectId: 'asan-yab-356f7',
    storageBucket: 'asan-yab-356f7.appspot.com',
    iosBundleId: 'com.example.asanYab',
  );
}
