// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC3SItuSWy3eBzydRlRAN36Ib61xJls9Y',
    appId: '1:525036166886:web:9c18b431cf5014f6fea527',
    messagingSenderId: '525036166886',
    projectId: 'asan-yab',
    authDomain: 'asan-yab.firebaseapp.com',
    storageBucket: 'asan-yab.appspot.com',
    measurementId: 'G-JKXF7FT16X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANccJ4SzQJxS5jGzN8zNEOigxQ0_nWdFU',
    appId: '1:525036166886:android:e77723bb4cdd4fd6fea527',
    messagingSenderId: '525036166886',
    projectId: 'asan-yab',
    storageBucket: 'asan-yab.appspot.com',
  );
}
