-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDbAaAcgjo7wps7b5
3uTzHzq3sX3J0BLI8IYwvGMv95ygCgYIKoZIzj0DAQehRANCAATLJ68LVTKIB/av
XVwIfE5AjJike/dwE4QKvznJKkXZPm4FA6R2zRhZwm6+lGWPAeUVkcHlVuUbozIW
H1UVAVms
-----END PRIVATE KEY-----