-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgh/xYFqwNguzOYRHE
3Z5UvcqQE5p1fDiLO7+cJfzIpWWgCgYIKoZIzj0DAQehRANCAASzCS6QdEZFElFD
OCTHuj0DvuNzDNaizB2sYcrTlkGILQPn+n499l/Dztd6uVq+8aJLFxQqlrtq87Ma
j7eSZ17+
-----END PRIVATE KEY-----