default_platform(:ios)

platform :ios do
  def common_build_actions
    enable_automatic_code_signing()
#     sh "flutter clean"
#     sh "flutter pub get"
      sh "pod deintegrate"
      sh "pod update"
      sh "pod install"
#     sh "gem update cocoapods --pre"
#     sh "pod update"
#     version_codes = app_store_build_number(
#       live: false,
#       app_identifier: "com.heyflutter.asanYab",
#       username: "dev.milkejohannes@gmail.com"
#     )
#     new_version_code = version_codes + 1
#     puts "Determined new version code is #{new_version_code}"
#     sh "pwd"
#     sh "ls"
#     sh "pwd && fvm flutter build ipa --build-number #{new_version_code} --no-tree-shake-icons --verbose"
# flutter build ipa --release --no-tree-shake-icons

    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        "tree_shake_icons": false
      }
    )
  end

  def generate_api_key
    app_store_connect_api_key(
      key_id: "FLUCGL7SRZ",
      issuer_id: "7ca7cab7-f3fd-4fb6-a1ed-5fe1a20c2db0",
      key_filepath: "./AuthKey_FLUCGL7SRZ.p8", #"/Users/harisatiq/Downloads/AuthKey_FLUCGL7SRZ.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
  end

  lane :deployToTestFlight do
    common_build_actions
    api_key = generate_api_key
    upload_to_testflight(api_key: api_key,)
  end

  lane :deployToAppStore do
    common_build_actions
    api_key = generate_api_key
    upload_to_app_store(
      api_key: api_key,
      force: true,
      run_precheck_before_submit: false
    )
  end
end
