default_platform(:android)

platform :android do
   desc "Deploy app bundle to play store"
      lane :deploy_android do |options|
        track = options[:production] ? 'production' : options[:alpha] ? 'alpha' : 'internal'
        puts "Determined track #{track}"
        version_codes = google_play_track_version_codes(
          track: "#{track}",
        )
        new_version_code = version_codes.last + 10
        puts "Determined new version code is #{new_version_code}"
        sh "pwd && cd /home/runner/work/asan_yab/asan_yab && flutter build appbundle --build-number #{new_version_code} --no-tree-shake-icons"
        upload_to_play_store(
             track: "#{track}",
             aab: '../build/app/outputs/bundle/release/app-release.aab',
             skip_upload_images: true,
             skip_upload_screenshots: true,
        )
    end
end