name: iOS Deploy
on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.2.0"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bundle install
        run: cd ./ios && bundle install
      - name: Set Fastlane environment to non-interactive
        run: echo "FASTLANE_OPT_OUT_USAGE=1" >> $GITHUB_ENV
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
      - name: pod install
        run: pod install
      - run: flutter clean
      - run: flutter pub get
      - name: Build and Deploy to App Store
        run: |
          flutter pub get
          if [ ${{ github.ref }} = 'refs/heads/production' ]; then
            fastlane deployToTestFlight
          else
            fastlane deployToTestFlight
          fi
          # fastlane deployToTestFlight
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
          FASTLANE_APPLE_EMAIL_ID: ${{ secrets.FASTLANE_APPLE_EMAIL_ID }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        working-directory: ios
