name: iOS Deploy
on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install bundler
        run: gem install bundler

      - name: Install Fastlane
        run: bundle install

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Set Fastlane environment to non-interactive
        run: echo "FASTLANE_OPT_OUT_USAGE=1" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6

      - name: Build and Deploy to TestFlight
        run: |
          flutter pub get
          bundle exec fastlane deployToTestFlight
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
          FASTLANE_APPLE_EMAIL_ID: ${{ secrets.FASTLANE_APPLE_EMAIL_ID }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        working-directory: ios
