name: iOS Deploy
on:
  push:
    branches:
      - master
      - production
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.2"
      - name: install fastlane
        run: sudo gem install fastlane
      - name: Set Fastlane environment to non-interactive
        run: echo "FASTLANE_OPT_OUT_USAGE=1" >> $GITHUB_ENV
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Set FLUTTER_ROOT
        run: echo "FLUTTER_ROOT=/Users/runner/hostedtoolcache/flutter/stable-3.10.6-x64" >> $GITHUB_ENV
      - name: Set FASTLANE_SESSION
        run: echo "FASTLANE_SESSION=${{ secrets.FASTLANE_SESSION }}" >> $GITHUB_ENV
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clear Xcode Cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/CocoaPods
      - name: Build and Deploy to App store
        run: |
          cd ..
          flutter clean
          flutter pub get
          cd ios
          gem install cocoapods
          bundle install
          echo installing pods
          pod install
          echo updating pods
          echo running lane now
          if [ ${{ github.ref }} = 'refs/heads/production' ]; then
            bundle exec fastlane deployToAppStore
          else
            bundle exec fastlane deployToTestFlight
          fi

        shell: bash
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
          FASTLANE_APPLE_EMAIL_ID: ${{ secrets.FASTLANE_APPLE_EMAIL_ID }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        working-directory: ios