name: iOS Deploy
on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.4"

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
        
#      - name: Select Xcode version
#        run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      - name: Bundle install
        run: cd ./ios && bundle install
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set Fastlane environment to non-interactive
        run: echo "FASTLANE_OPT_OUT_USAGE=1" >> $GITHUB_ENV
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      #  - name: Github Login
      #   run: gh auth login --with-token < ./ios/mytoken.txt
      - name: Clone repo
        run: git clone git@github.com:HarisAtiq2762/ios-certificates.git /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20231002-6471-1azqkg1

      - name: Build and Deploy to App Store
        run: |
          flutter pub get
          cd ./ios && pod install
          set -x
          fastlane deployToTestFlight
#          if [ ${{ github.ref }} = 'refs/heads/production' ]; then
#            fastlane deployToTestFlight
#          else
#            fastlane deployToTestFlight
#          fi
#          # fastlane deployToTestFlight
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
          FASTLANE_APPLE_EMAIL_ID: ${{ secrets.FASTLANE_APPLE_EMAIL_ID }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        working-directory: ios


#name: iOS Deploy
#on:
#  push:
#    branches:
#      - master
#      - production
#
#jobs:
#  build:
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Ruby
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#
#      - name: Install bundler
#        run: gem install bundler
#
#      - name: Install Fastlane
#        run: bundle install
#
#      - name: Bundle install
#        run: cd ./ios && bundle install
#
#      - name: Set Fastlane environment to non-interactive
#        run: echo "FASTLANE_OPT_OUT_USAGE=1" >> $GITHUB_ENV
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: 3.10.6
#
#      - name: Build and Deploy to TestFlight
#        run: |
#          flutter pub get
#          bundle exec fastlane deployToTestFlight
#        env:
#          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
#          BUNDLE_IDENTIFIER: ${{ secrets.BUNDLE_IDENTIFIER }}
#          FASTLANE_APPLE_EMAIL_ID: ${{ secrets.FASTLANE_APPLE_EMAIL_ID }}
#          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
#          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
#          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
#          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
#          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#        working-directory: ios


